Repository CrowdStrike/falcon-scripts, pull requests merged in 2023-01, with the labels that each got.

#125 Add ci testing linux
  .github/workflows/ci-linux.yml
  molecule/bash_install/converge.yml
  molecule/bash_install/molecule.yml
  molecule/bash_install/prepare.yml
  molecule/bash_install/verify.yml
  molecule/bash_install_decrement/converge.yml
  molecule/bash_install_decrement/molecule.yml
  molecule/bash_install_decrement/prepare.yml
  molecule/bash_install_decrement/verify.yml
  molecule/bash_install_only/converge.yml
  molecule/bash_install_only/molecule.yml
  molecule/bash_install_only/prepare.yml
  molecule/bash_install_only/verify.yml
  molecule/bash_install_policy/converge.yml
  molecule/bash_install_policy/molecule.yml
  molecule/bash_install_policy/prepare.yml
  molecule/bash_install_policy/verify.yml
Labels: bash, linux

#130 Adding status badge for current integration tests
  README.md
Labels: documentation

#136 Update powershell install/uninstaller
  .github/workflows/ci-windows.yml
  molecule/pwsh_install_policy/converge.yml
  molecule/pwsh_install_policy/molecule.yml
  molecule/pwsh_install_policy/verify.yml
  powershell/PSScriptAnalyzerSettings.psd1
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
Labels: ok-to-test
