Repository CrowdStrike/falcon-scripts, pull requests merged in 2024-12, with the labels that each got.

#391 chore: prefer the use of Host Retention Policies
  bash/install/README.md
  bash/install/falcon-linux-uninstall.sh
  powershell/install/README.md
  powershell/install/falcon_windows_uninstall.ps1
Labels: documentation

#393 fix(pwsh): allow getaccess token to run w/o priv or existing installer
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
Labels: ok-to-test, bugfix

#394 chore: bump v1.7.2
  bash/containers/falcon-container-sensor-pull/README.md
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
  bash/install/README.md
  bash/install/falcon-linux-install.sh
  bash/install/falcon-linux-uninstall.sh
  powershell/install/README.md
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
  powershell/migrate/README.md
  powershell/migrate/falcon_windows_migrate.ps1
Labels: release
