Repository CrowdStrike/falcon-scripts, pull requests merged in 2024-10, with the labels that each got.

#370 fix(container-pull-script): allows list tags w/o container runtime
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Labels: bugfix

#367 Support busybox
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Labels: bash, container

#372 chore(container-pull-script): echo destination path and update list-tags verbiage
  bash/containers/falcon-container-sensor-pull/README.md
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Labels: enhancement, bash, container

#375 Create stale.yml
  .github/workflows/stale.yml
Labels: ci/cd

#377 fix(pwsh): add missing '/' to error message for oauth2
  powershell/install/falcon_windows_install.ps1
  powershell/migrate/falcon_windows_migrate.ps1
Labels: bugfix
