Repository CrowdStrike/falcon-scripts, pull requests merged in 2025-04, with the labels that each got.

#417 chore: bump v1.7.4
  bash/containers/falcon-container-sensor-pull/README.md
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
  bash/install/README.md
  bash/install/falcon-linux-install.sh
  bash/install/falcon-linux-uninstall.sh
  powershell/install/README.md
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
  powershell/migrate/README.md
  powershell/migrate/falcon_windows_migrate.ps1
Labels: next release

#422 feat: allow user-agent string to be customizable
  bash/install/falcon-linux-install.sh
  bash/install/falcon-linux-uninstall.sh
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
  powershell/migrate/falcon_windows_migrate.ps1
Labels: enhancement

#424 feat(uninstall bash): add maintenance token functionality for Linux
  bash/install/README.md
  bash/install/falcon-linux-uninstall.sh
Labels: enhancement, bash, linux

#425 chore: update GPG key for 2025 sensor 7.24
  bash/install/falcon-linux-install.sh
Labels: ok-to-test

#427 chore: bump v1.8.0
  bash/containers/falcon-container-sensor-pull/README.md
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
  bash/install/README.md
  bash/install/falcon-linux-install.sh
  bash/install/falcon-linux-uninstall.sh
  bash/migrate/README.md
  bash/migrate/falcon-linux-migrate.sh
  powershell/install/README.md
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
  powershell/migrate/README.md
  powershell/migrate/falcon_windows_migrate.ps1
Labels: next release

#429 Readme updates
  README.md
  bash/containers/falcon-container-sensor-pull/README.md
  powershell/install/README.md
  powershell/migrate/README.md
Labels: documentation

#430 ci: increase timeout
  .github/workflows/bash_install.yml
  .github/workflows/bash_install_decrement.yml
  .github/workflows/bash_install_only.yml
  .github/workflows/bash_install_policy.yml
  .github/workflows/bash_migrate.yml
  .github/workflows/pwsh_install_ccid.yml
  .github/workflows/pwsh_install_policy.yml
  .github/workflows/pwsh_migrate.yml
  .github/workflows/pwsh_uninstall.yml
Labels: ci/cd

#431 feat: add support for gov-2
  bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Labels: bash, container

#432 feat: add support for gov-2 for install scripts
  bash/install/falcon-linux-install.sh
  bash/install/falcon-linux-uninstall.sh
  bash/migrate/falcon-linux-migrate.sh
  powershell/install/falcon_windows_install.ps1
  powershell/install/falcon_windows_uninstall.ps1
  powershell/migrate/falcon_windows_migrate.ps1
Labels: enhancement, bash, linux
